### ISSUE TITLE
bug: potential bug for quizzes on Arweave 101 lesson 2 

### ISSUE THREAD

**Issue by kempsterrrr** [Developer-DAO/academy-turbo#284]
![Screenshot 2024-09-16 at 11 27 48](https://github.com/user-attachments/assets/39b3d153-1355-4687-a8ef-dbd73e6c5461)

We have had this report from the AR.IO team. I haven't had time to validate this yet but sharing so we can look into it.

@wolovim was away over the weekend so unsure if he's had the time. @kay-is would you mind checking the questions to see if there is an issue?

**Comment by kay-is** [comment]
@kempsterrrr I reviewed the questions and quiz from Arweave 101 Lesson 2 and couldn't find any inconsistencies.

**Comment by kempsterrrr** [comment]
Thanks @kay-is - I will push back to see if we can get more detail. If not, we can close it.

**Comment by kay-is** [comment]
It could be an issue with differing implementations for quizzes and questions.

I think, someone like @Markkos89 is better suited to check if that's the case.

**Comment by kempsterrrr** [comment]
I'm not exactly sure. What it sounds like the user is suggesting is the quiz answers in the check point quizzes didn't match the answers in the final quiz. @kay-is checked the data and looked ok so wondering if it could be a code issue maybe?

If we can't recreate it we can go back and ask for more info.

**Comment by Markkos89** [comment]
It's easy, go back to them for more information asap because we are only guessing based on a single sentence from a screenshot :laughing: 

It's easy because If it's a code issue it should be happening **in all checkpoint quizzes** and **in all quizzes** because all the lessons use the same component with the same logic and the same format for the question .json and quiz .json files. Super easy.

Whenever you have more information let me know

**Comment by kempsterrrr** [comment]
A little more context, I have aksed the AR.IO team to connect us with the user:

![image](https://github.com/user-attachments/assets/d8af3f0b-8c4f-46bc-ac59-2a7f4db34adf)

**Comment by markmakerxyz** [comment]
HI - It is perfectly possible that I may be failing the quiz repeatedly because I do not completely understand what I am reading, or something like that. After attempting the quiz (open book with the article open in a separate browser), I opened the test quiz in a separate browser to push correct answers to the main quiz so I could move forward. 
I still couldn't get better than 5 incorrect answers.
So I was wondering if there is possibly an error with the quiz.

**Comment by markmakerxyz** [comment]
If the quiz is working properly, I truly apologize for wasting your time.

**Comment by Markkos89** [comment]
Hi @markmakerxyz Thank you a lot for reaching to us with this. 
I just tested the Final Quiz of the Lesson 2 of the Arweave-101 track and it's working as expected:

![image](https://github.com/user-attachments/assets/08f40b53-4e8b-45db-845c-8be5aae87633)

There is nothing to apologize mate, thanks again for bringing your issue to us :raised_hands: 
If there is something else we can help you out don't hesitate to let us know :wink:

**Comment by markmakerxyz** [comment]
Yikes - thanks for looking into it :)

**Comment by markmakerxyz** [comment]
i will reach out to @almostgreat to do that

**Comment by kempsterrrr** [comment]
thanks chaps 🫡
